### PR TITLE
recipes-zephyr: update firmwares

### PR DESCRIPTION
**Pull request by aaillet**
They have been generated from:
https://github.com/iotbzh/zephyr
rev:2021-06-18

Signed-off-by: Aymeric Aillet <aymeric.aillet@iot.bzh>

### CODE REVIEW

**Comment by aaillet** [comment]
DNM : need to be tested on h3ulcb and ebisu

**Comment by julien-massot** [comment]
tested on ebisu ok

**Comment by aaillet** [comment]
Updated with 2021-06-21 rev

**Comment by julien-massot** [comment]
tested ok on H3ULCB

**Pull request merged**
